"""initial_schema

Revision ID: 4316d9f2c447
Revises: 
Create Date: 2026-08-09 00:03:49.592247

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '4316d9f2c447'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
